// this source generated by GenAI v2.9.4 
import API from "../../utils/api";

const PfCltM1Det = {

    insertRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/pfCltM1Det/insertRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    insertBatch: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/pfCltM1Det/insertBatch", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    updateRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/pfCltM1Det/updateRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    updateBatch: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/pfCltM1Det/updateBatch", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getRecord: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfCltM1Det/getRecord";
            const filterUrl = PfCltM1Det.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfCltM1Det.formatRecord(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatRecord: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({


                id: d.id,
                clt_name: d.clt_name,
                clt_type_id: d.clt_type_id,
                cin_nr: d.cin_nr,
                gst_nr: d.gst_nr,
                lc_status_id: d.lc_status_id,
                is_active: d.is_active,
                created_at: d.created_at,
                created_by: d.created_by,
                tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getPageDet: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfCltM1Det/getPageDet";
            const filterUrl = PfCltM1Det.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfCltM1Det.formatPageDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatPageDet: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                comment_cnt: d.comment_cnt == null ? 0 : d.comment_cnt,


                id: d.id,
                clt_name: d.clt_name,
                clt_type_id: d.clt_type_id,
                cin_nr: d.cin_nr,
                gst_nr: d.gst_nr,
                lc_status_id: d.lc_status_id,
                is_active: d.is_active,
                created_at: d.created_at,
                created_by: d.created_by,
                tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },
    getAuditData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfCltM1Det/getAudit";
            const filterUrl = PfCltM1Det.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    console.log("res.data: ", res.data);
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getFilteredData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfCltM1Det/getFilteredData";
            const filterUrl = PfCltM1Det.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfCltM1Det.formatFiltered(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatFiltered: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({


                id: d.id,
                clt_name: d.clt_name,
                clt_type_id: d.clt_type_id,
                cin_nr: d.cin_nr,
                gst_nr: d.gst_nr,
                lc_status_id: d.lc_status_id,
                is_active: d.is_active,
                created_at: d.created_at,
                created_by: d.created_by,
                tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getFilterUrl: (filter) => {
        let url = "";

        if (filter !== undefined) {
            if (filter.com_id !== undefined) {
                url += "com_id=" + filter.com_id + "&";
            }

            if (filter.id !== undefined) {
                url += "id=" + filter.id + "&";
            }
            if (filter.clt_name !== undefined) {
                url += "clt_name=" + filter.clt_name + "&";
            }
            if (filter.clt_type_id !== undefined) {
                url += "clt_type_id=" + filter.clt_type_id + "&";
            }
            if (filter.cin_nr !== undefined) {
                url += "cin_nr=" + filter.cin_nr + "&";
            }
            if (filter.gst_nr !== undefined) {
                url += "gst_nr=" + filter.gst_nr + "&";
            }
            if (filter.lc_status_id !== undefined) {
                url += "lc_status_id=" + filter.lc_status_id + "&";
            }
            if (filter.is_active !== undefined) {
                url += "is_active=" + filter.is_active + "&";
            }
            if (filter.created_at !== undefined) {
                url += "created_at=" + filter.created_at + "&";
            }
            if (filter.created_by !== undefined) {
                url += "created_by=" + filter.created_by + "&";
            }
            if (filter.tnnt_id !== undefined) {
                url += "tnnt_id=" + filter.tnnt_id + "&";
            }
            if (filter.ref_id !== undefined) {
                url += "ref_id=" + filter.ref_id + "&";
            }
            //param_value

        }
        return url;
    },
};

export default PfCltM1Det;