// this source generated by GenAI v2.9.4 
import API from "../../utils/api";

const PfConstOption = {

    insertRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/pfConstOption/insertRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

        insertMulti: (data) =>
            new Promise(function (resolve, reject) {
                API.post("/pfConstOption/insertMulti", data, {
                    headers: {
                        "x-access-token": global.config.accessToken,
                    },
                })
                    .then(async (res) => {
                        if (res.status === 200) {
                            resolve(res.data);
                        } else {
                            reject(res.data.msg);
                        }
                    })
                    .catch((err) => {
                        reject(err);
                    });
            }),

    updateRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/pfConstOption/updateRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),
    
	getRecord: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfConstOption/getRecord";
            const filterUrl = PfConstOption.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfConstOption.formatRecord(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatRecord: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            const_type_id: d.const_type_id,
            const_type_name: d.const_type_name,
            option_name : d.option_name ,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

	getPageDet: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfConstOption/getPageDet";
            const filterUrl = PfConstOption.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfConstOption.formatPageDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatPageDet: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                comment_cnt: d.comment_cnt == null ? 0 : d.comment_cnt,
				

            id: d.id,
            const_type_id: d.const_type_id,
            const_type_name: d.const_type_name,
            option_name : d.option_name ,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },


    getConstOptions: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfConstOption/getConstOptions";
            const filterUrl = PfConstOption.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfConstOption.formatDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatDet: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
            id: d.id,
            option_name : d.option_name,
            });
        }
        return formatted;
    },


    getAuditData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfConstOption/getAudit";
            const filterUrl = PfConstOption.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    console.log("res.data: ", res.data);
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getFilteredData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfConstOption/getFilteredData";
            const filterUrl = PfConstOption.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfConstOption.formatFiltered(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatFiltered: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            const_type_id: d.const_type_id,
            const_type_name: d.const_type_name,
            option_name : d.option_name ,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getFilterUrl: (filter) => {
        let url = "";

        if (filter !== undefined) {
			if (filter.com_id !== undefined) {
              url += "com_id=" + filter.com_id + "&";
            }

if (filter.id !== undefined) {
    url += "id=" + filter.id + "&";
}
if (filter.intl_id !== undefined) {
    url += "intl_id=" + filter.intl_id + "&";
}
if (filter.const_type_id !== undefined) {
    url += "const_type_id=" + filter.const_type_id + "&";
}
if (filter.option_name  !== undefined) {
    url += "option_name =" + filter.option_name  + "&";
}
if (filter.lc_status_id !== undefined) {
    url += "lc_status_id=" + filter.lc_status_id + "&";
}
if (filter.is_active !== undefined) {
    url += "is_active=" + filter.is_active + "&";
}
if (filter.created_at !== undefined) {
    url += "created_at=" + filter.created_at + "&";
}
if (filter.created_by !== undefined) {
    url += "created_by=" + filter.created_by + "&";
}
if (filter.tnnt_id !== undefined) {
    url += "tnnt_id=" + filter.tnnt_id + "&";
}
if (filter.ref_id !== undefined) { 
 url += "ref_id=" + filter.ref_id + "&";
}
			//param_value
            
        }
        return url;
    },
};

export default PfConstOption;