// this source generated by GenAI v2.9.4 
import API from "../../utils/api";

const PfEndPointDet = {

    insertRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/pfEndPointDet/insertRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    updateRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/pfEndPointDet/updateRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),
    
	getRecord: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEndPointDet/getRecord";
            const filterUrl = PfEndPointDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfEndPointDet.formatRecord(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatRecord: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            ms_id: d.ms_id,
            end_point: d.end_point,
            api_method_id: d.api_method_id,
            url: d.url,
            header_token: d.header_token,
            req_msg: d.req_msg,
            exp_resp_msg: d.exp_resp_msg,
            act_resp_msg: d.act_resp_msg,
            test_result: d.test_result,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

	getPageDet: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEndPointDet/getPageDet";
            const filterUrl = PfEndPointDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfEndPointDet.formatPageDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatPageDet: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                comment_cnt: d.comment_cnt == null ? 0 : d.comment_cnt,
				

            id: d.id,
            ms_id: d.ms_id,
            end_point: d.end_point,
            api_method_id: d.api_method_id,
            url: d.url,
            header_token: d.header_token,
            req_msg: d.req_msg,
            exp_resp_msg: d.exp_resp_msg,
            act_resp_msg: d.act_resp_msg,
            test_result: d.test_result,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },
    getAuditData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEndPointDet/getAudit";
            const filterUrl = PfEndPointDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    console.log("res.data: ", res.data);
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getFilteredData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEndPointDet/getFilteredData";
            const filterUrl = PfEndPointDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfEndPointDet.formatFiltered(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatFiltered: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            ms_id: d.ms_id,
            end_point: d.end_point,
            api_method_id: d.api_method_id,
            url: d.url,
            header_token: d.header_token,
            req_msg: d.req_msg,
            exp_resp_msg: d.exp_resp_msg,
            act_resp_msg: d.act_resp_msg,
            test_result: d.test_result,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getFilterUrl: (filter) => {
        let url = "";

        if (filter !== undefined) {
			if (filter.com_id !== undefined) {
              url += "com_id=" + filter.com_id + "&";
            }

if (filter.id !== undefined) {
    url += "id=" + filter.id + "&";
}
if (filter.ms_id !== undefined) {
    url += "ms_id=" + filter.ms_id + "&";
}
if (filter.end_point !== undefined) {
    url += "end_point=" + filter.end_point + "&";
}
if (filter.api_method_id !== undefined) {
    url += "api_method_id=" + filter.api_method_id + "&";
}
if (filter.url !== undefined) {
    url += "url=" + filter.url + "&";
}
if (filter.header_token !== undefined) {
    url += "header_token=" + filter.header_token + "&";
}
if (filter.req_msg !== undefined) {
    url += "req_msg=" + filter.req_msg + "&";
}
if (filter.exp_resp_msg !== undefined) {
    url += "exp_resp_msg=" + filter.exp_resp_msg + "&";
}
if (filter.act_resp_msg !== undefined) {
    url += "act_resp_msg=" + filter.act_resp_msg + "&";
}
if (filter.test_result !== undefined) {
    url += "test_result=" + filter.test_result + "&";
}
if (filter.lc_status_id !== undefined) {
    url += "lc_status_id=" + filter.lc_status_id + "&";
}
if (filter.is_active !== undefined) {
    url += "is_active=" + filter.is_active + "&";
}
if (filter.created_at !== undefined) {
    url += "created_at=" + filter.created_at + "&";
}
if (filter.created_by !== undefined) {
    url += "created_by=" + filter.created_by + "&";
}
if (filter.tnnt_id !== undefined) {
    url += "tnnt_id=" + filter.tnnt_id + "&";
}
if (filter.ref_id !== undefined) { 
 url += "ref_id=" + filter.ref_id + "&";
}
			//param_value
            
        }
        return url;
    },
};

export default PfEndPointDet;