// this source generated by GenAI v2.9.4 
import API from "../../utils/api";

const PfEventDet = {

    insertRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/pfEventDet/insertRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    updateRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/pfEventDet/updateRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),
    
	getRecord: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEventDet/getRecord";
            const filterUrl = PfEventDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfEventDet.formatRecord(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatRecord: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            clt_ref_id: d.clt_ref_id,
            event_descr: d.event_descr,
            com_id: d.com_id,
            channel_notif: d.channel_notif,
            channel_notif_msg: d.channel_notif_msg,
            channel_email: d.channel_email,
            channel_email_templ: d.channel_email_templ,
            channel_wapp: d.channel_wapp,
            channel_wapp_msg: d.channel_wapp_msg,
            channel_push_notif: d.channel_push_notif,
            channel_push_msg: d.channel_push_msg,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

	getPageDet: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEventDet/getPageDet";
            const filterUrl = PfEventDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfEventDet.formatPageDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatPageDet: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                comment_cnt: d.comment_cnt == null ? 0 : d.comment_cnt,
				

            id: d.id,
            clt_ref_id: d.clt_ref_id,
            event_descr: d.event_descr,
            com_id: d.com_id,
            channel_notif: d.channel_notif,
            channel_notif_msg: d.channel_notif_msg,
            channel_email: d.channel_email,
            channel_email_templ: d.channel_email_templ,
            channel_wapp: d.channel_wapp,
            channel_wapp_msg: d.channel_wapp_msg,
            channel_push_notif: d.channel_push_notif,
            channel_push_msg: d.channel_push_msg,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },
    getAuditData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEventDet/getAudit";
            const filterUrl = PfEventDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    console.log("res.data: ", res.data);
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getFilteredData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/pfEventDet/getFilteredData";
            const filterUrl = PfEventDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(PfEventDet.formatFiltered(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatFiltered: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            clt_ref_id: d.clt_ref_id,
            event_descr: d.event_descr,
            com_id: d.com_id,
            channel_notif: d.channel_notif,
            channel_notif_msg: d.channel_notif_msg,
            channel_email: d.channel_email,
            channel_email_templ: d.channel_email_templ,
            channel_wapp: d.channel_wapp,
            channel_wapp_msg: d.channel_wapp_msg,
            channel_push_notif: d.channel_push_notif,
            channel_push_msg: d.channel_push_msg,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getFilterUrl: (filter) => {
        let url = "";

        if (filter !== undefined) {
			if (filter.com_id !== undefined) {
              url += "com_id=" + filter.com_id + "&";
            }

if (filter.id !== undefined) {
    url += "id=" + filter.id + "&";
}
if (filter.clt_ref_id !== undefined) {
    url += "clt_ref_id=" + filter.clt_ref_id + "&";
}
if (filter.event_descr !== undefined) {
    url += "event_descr=" + filter.event_descr + "&";
}
if (filter.com_id !== undefined) {
    url += "com_id=" + filter.com_id + "&";
}
if (filter.channel_notif !== undefined) {
    url += "channel_notif=" + filter.channel_notif + "&";
}
if (filter.channel_notif_msg !== undefined) {
    url += "channel_notif_msg=" + filter.channel_notif_msg + "&";
}
if (filter.channel_email !== undefined) {
    url += "channel_email=" + filter.channel_email + "&";
}
if (filter.channel_email_templ !== undefined) {
    url += "channel_email_templ=" + filter.channel_email_templ + "&";
}
if (filter.channel_wapp !== undefined) {
    url += "channel_wapp=" + filter.channel_wapp + "&";
}
if (filter.channel_wapp_msg !== undefined) {
    url += "channel_wapp_msg=" + filter.channel_wapp_msg + "&";
}
if (filter.channel_push_notif !== undefined) {
    url += "channel_push_notif=" + filter.channel_push_notif + "&";
}
if (filter.channel_push_msg !== undefined) {
    url += "channel_push_msg=" + filter.channel_push_msg + "&";
}
if (filter.lc_status_id !== undefined) {
    url += "lc_status_id=" + filter.lc_status_id + "&";
}
if (filter.is_active !== undefined) {
    url += "is_active=" + filter.is_active + "&";
}
if (filter.created_at !== undefined) {
    url += "created_at=" + filter.created_at + "&";
}
if (filter.created_by !== undefined) {
    url += "created_by=" + filter.created_by + "&";
}
if (filter.tnnt_id !== undefined) {
    url += "tnnt_id=" + filter.tnnt_id + "&";
}
if (filter.ref_id !== undefined) { 
 url += "ref_id=" + filter.ref_id + "&";
}
			//param_value
            
        }
        return url;
    },
};

export default PfEventDet;