// this source generated by GenAI v2.9.4 
import API from "../../utils/api";
import moment from "moment" ; 

const TaToDoDet = {

    insertRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/taToDoDet/insertRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    updateRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/taToDoDet/updateRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),
    
	getRecord: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/taToDoDet/getRecord";
            const filterUrl = TaToDoDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(TaToDoDet.formatRecord(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatRecord: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            task_title: d.task_title,
            task_descr: d.task_descr,
            task_date: d.task_date == null ? "" : d.task_date,
            task_time: d.task_time,
            priority_id: d.priority_id,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

	getPageDet: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/taToDoDet/getPageDet";
            const filterUrl = TaToDoDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(TaToDoDet.formatPageDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatPageDet: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                comment_cnt: d.comment_cnt == null ? 0 : d.comment_cnt,
				

            id: d.id,
            task_title: d.task_title,
            task_descr: d.task_descr,
            task_date: d.task_date == null ? "" : d.task_date,
            task_time: d.task_time,
            priority_id: d.priority_id,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },
    getAuditData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/taToDoDet/getAudit";
            const filterUrl = TaToDoDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    console.log("res.data: ", res.data);
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getFilteredData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/taToDoDet/getFilteredData";
            const filterUrl = TaToDoDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(TaToDoDet.formatFiltered(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatFiltered: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            task_title: d.task_title,
            task_descr: d.task_descr,
            task_date: d.task_date == null ? "" : d.task_date,
            task_time: d.task_time,
            priority_id: d.priority_id,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getFilterUrl: (filter) => {
        let url = "";

        if (filter !== undefined) {
			if (filter.com_id !== undefined) {
              url += "com_id=" + filter.com_id + "&";
            }

if (filter.id !== undefined) {
    url += "id=" + filter.id + "&";
}
if (filter.task_title !== undefined) {
    url += "task_title=" + filter.task_title + "&";
}
if (filter.task_descr !== undefined) {
    url += "task_descr=" + filter.task_descr + "&";
}
if (filter.task_date !== undefined) {
    url += "task_date=" + filter.task_date + "&";
}
if (filter.task_time !== undefined) {
    url += "task_time=" + filter.task_time + "&";
}
if (filter.priority_id !== undefined) {
    url += "priority_id=" + filter.priority_id + "&";
}
if (filter.clt_ref_id !== undefined) {
    url += "clt_ref_id=" + filter.clt_ref_id + "&";
}
if (filter.lc_status_id !== undefined) {
    url += "lc_status_id=" + filter.lc_status_id + "&";
}
if (filter.is_active !== undefined) {
    url += "is_active=" + filter.is_active + "&";
}
if (filter.created_at !== undefined) {
    url += "created_at=" + filter.created_at + "&";
}
if (filter.created_by !== undefined) {
    url += "created_by=" + filter.created_by + "&";
}
if (filter.tnnt_id !== undefined) {
    url += "tnnt_id=" + filter.tnnt_id + "&";
}
if (filter.ref_id !== undefined) { 
 url += "ref_id=" + filter.ref_id + "&";
}
			//param_value
            
        }
        return url;
    },
};

export default TaToDoDet;