// this source generated by GenAI pythonProject
import API from "../../utils/api";
import moment from "moment" ; 

const SdTestCycleDet = {

    insertRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/sdTestCycleDet/insertRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    updateRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/sdTestCycleDet/updateRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),
    
	getRecord: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdTestCycleDet/getRecord";
            const filterUrl = SdTestCycleDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(SdTestCycleDet.formatRecord(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatRecord: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            proj_id: d.proj_id,
            proj_name: d.proj_name,
            cycle_name: d.cycle_name,
            // start_date: d.start_date == null ? "" : d.start_date,
            // end_date: d.end_date == null ? "" : d.end_date,
            start_date: d.start_date == null ? "" : moment(d.start_date).format("DD/MM/YYYY"),
            end_date: d.end_date == null ? null : moment(d.end_date).format("DD/MM/YYYY"),
            test_lead: d.test_lead,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

	getPageDet: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdTestCycleDet/getPageDet";
            const filterUrl = SdTestCycleDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(SdTestCycleDet.formatPageDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatPageDet: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                comment_cnt: d.comment_cnt == null ? 0 : d.comment_cnt,
				

            id: d.id,
            proj_id: d.proj_id,
            proj_name: d.proj_name,
            cycle_name: d.cycle_name,
            start_date: d.start_date == null ? null : moment(d.start_date).format("DD-MMM-YYYY"),
            end_date: d.end_date == null ? null : moment(d.end_date).format("DD-MMM-YYYY"),
            test_lead: d.test_lead,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },
    getAuditData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdTestCycleDet/getAudit";
            const filterUrl = SdTestCycleDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    console.log("res.data: ", res.data);
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getFilteredData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdTestCycleDet/getFilteredData";
            const filterUrl = SdTestCycleDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(SdTestCycleDet.formatFiltered(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatFiltered: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            proj_id: d.proj_id,
            proj_name: d.proj_name,
            cycle_name: d.cycle_name,
            start_date: d.start_date == null ? "" : moment(d.start_date).format("DD/MM/YYYY"),
            end_date: d.end_date == null ? null : moment(d.end_date).format("DD/MM/YYYY"),
            test_lead: d.test_lead,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getFilterUrl: (filter) => {
        let url = "";

        if (filter !== undefined) {
			if (filter.com_id !== undefined) {
              url += "com_id=" + filter.com_id + "&";
            }

if (filter.id !== undefined) {
    url += "id=" + filter.id + "&";
}
if (filter.proj_id !== undefined) {
    url += "proj_id=" + filter.proj_id + "&";
}
if (filter.cycle_name !== undefined) {
    url += "cycle_name=" + filter.cycle_name + "&";
}
if (filter.start_date !== undefined) {
    url += "start_date=" + filter.start_date + "&";
}
if (filter.end_date !== undefined) {
    url += "end_date=" + filter.end_date + "&";
}
if (filter.test_lead !== undefined) {
    url += "test_lead=" + filter.test_lead + "&";
}
if (filter.clt_ref_id !== undefined) {
    url += "clt_ref_id=" + filter.clt_ref_id + "&";
}
if (filter.lc_status_id !== undefined) {
    url += "lc_status_id=" + filter.lc_status_id + "&";
}
if (filter.is_active !== undefined) {
    url += "is_active=" + filter.is_active + "&";
}
if (filter.created_at !== undefined) {
    url += "created_at=" + filter.created_at + "&";
}
if (filter.created_by !== undefined) {
    url += "created_by=" + filter.created_by + "&";
}
if (filter.tnnt_id !== undefined) {
    url += "tnnt_id=" + filter.tnnt_id + "&";
}
if (filter.ref_id !== undefined) { 
 url += "ref_id=" + filter.ref_id + "&";
}
			//param_value
            
        }
        return url;
    },
};

export default SdTestCycleDet;