// this source generated by GenAI pythonProject
import API from "../../utils/api";

const SdUsDet = {

    insertRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.post("/sdUsDetl/insertRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    if (res.status === 200) {
                        resolve(res.data);
                    } else {
                        reject(res.data.msg);
                    }
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    updateRecord: (data) =>
        new Promise(function (resolve, reject) {
            API.patch("/sdUsDetl/updateRecord", data, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),
    
	getRecord: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdUsDetl/getRecord";
            const filterUrl = SdUsDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(SdUsDet.formatRecord(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatRecord: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            us_name: d.us_name,
            descr: d.descr,
            feat_id: d.feat_id,
            feat_name: d.feat_name,
            us_as_a: d.us_as_a,
            us_i_want: d.us_i_want,
            us_so_that: d.us_so_that,
            us_bus_rational: d.us_bus_rational,
            us_type: d.us_type,
            templ_id: d.templ_id,
            proj_imp_status_id: d.proj_imp_status_id,
            imp_status_name: d.imp_status_name,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

	getPageDet: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdUsDetl/getPageDet";
            const filterUrl = SdUsDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(SdUsDet.formatPageDet(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatPageDet: (data) => {
        const formatted = [];

        for (let d of data) {
            console.log(data)
            formatted.push({
                comment_cnt: d.comment_cnt == null ? 0 : d.comment_cnt,
				

            id: d.id,
            us_name: d.us_name,
            descr: d.descr,
            feat_id: d.feat_id,
            feat_name: d.feat_name,
            us_as_a: d.us_as_a,
            us_i_want: d.us_i_want,
            us_so_that: d.us_so_that,
            us_bus_rational: d.us_bus_rational,
            us_type: d.us_type,
            templ_id: d.templ_id,
            proj_imp_status_id: d.proj_imp_status_id,
            imp_status_name: d.imp_status_name,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },
    getAuditData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdUsDetl/getAudit";
            const filterUrl = SdUsDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    console.log("res.data: ", res.data);
                    resolve(res.data);
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    getFilteredData: (filter) =>
        new Promise(function (resolve, reject) {
            const baseUrl = "/sdUsDetl/getFilteredData";
            const filterUrl = SdUsDet.getFilterUrl(filter);
            API.get(`${baseUrl}?${filterUrl}`, {
                headers: {
                    "x-access-token": global.config.accessToken,
                },
            })
                .then(async (res) => {
                    resolve(SdUsDet.formatFiltered(res.data));
                })
                .catch((err) => {
                    reject(err);
                });
        }),

    formatFiltered: (data) => {
        const formatted = [];

        for (let d of data) {
            formatted.push({
                

            id: d.id,
            us_name: d.us_name,
            descr: d.descr,
            feat_id: d.feat_id,
            feat_name: d.feat_name,
            us_as_a: d.us_as_a,
            us_i_want: d.us_i_want,
            us_so_that: d.us_so_that,
            us_bus_rational: d.us_bus_rational,
            us_type: d.us_type,
            templ_id: d.templ_id,
            proj_imp_status_id: d.proj_imp_status_id,
            imp_status_name: d.imp_status_name,
            clt_ref_id: d.clt_ref_id,
            lc_status_id: d.lc_status_id,
            is_active: d.is_active,
            created_at: d.created_at,
            created_by: d.created_by,
            tnnt_id: d.tnnt_id,

            });
        }
        return formatted;
    },

    getFilterUrl: (filter) => {
        let url = "";

        if (filter !== undefined) {
			if (filter.com_id !== undefined) {
              url += "com_id=" + filter.com_id + "&";
            }

if (filter.id !== undefined) {
    url += "id=" + filter.id + "&";
}
if (filter.us_name !== undefined) {
    url += "us_name=" + filter.us_name + "&";
}
if (filter.descr !== undefined) {
    url += "descr=" + filter.descr + "&";
}
if (filter.feat_id !== undefined) {
    url += "feat_id=" + filter.feat_id + "&";
}
if (filter.us_as_a !== undefined) {
    url += "us_as_a=" + filter.us_as_a + "&";
}
if (filter.us_i_want !== undefined) {
    url += "us_i_want=" + filter.us_i_want + "&";
}
if (filter.us_so_that !== undefined) {
    url += "us_so_that=" + filter.us_so_that + "&";
}
if (filter.us_bus_rational !== undefined) {
    url += "us_bus_rational=" + filter.us_bus_rational + "&";
}
if (filter.us_type !== undefined) {
    url += "us_type=" + filter.us_type + "&";
}
if (filter.templ_id !== undefined) {
    url += "templ_id=" + filter.templ_id + "&";
}
if (filter.proj_imp_status_id !== undefined) {
    url += "proj_imp_status_id=" + filter.proj_imp_status_id + "&";
}
if (filter.clt_ref_id !== undefined) {
    url += "clt_ref_id=" + filter.clt_ref_id + "&";
}
if (filter.lc_status_id !== undefined) {
    url += "lc_status_id=" + filter.lc_status_id + "&";
}
if (filter.is_active !== undefined) {
    url += "is_active=" + filter.is_active + "&";
}
if (filter.created_at !== undefined) {
    url += "created_at=" + filter.created_at + "&";
}
if (filter.created_by !== undefined) {
    url += "created_by=" + filter.created_by + "&";
}
if (filter.tnnt_id !== undefined) {
    url += "tnnt_id=" + filter.tnnt_id + "&";
}
if (filter.ref_id !== undefined) { 
 url += "ref_id=" + filter.ref_id + "&";
}
			//param_value
            
        }
        return url;
    },
};

export default SdUsDet;