// this source generated by GenAI v2.9.4 
import React from "react";
import moment from "moment";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import Swal from "sweetalert2";
import Colors from "../../constants/colors";
import styles from "../../styles/createcom.module.css";
import CustomInput from "../customInput/customInput";
import SampleHelper from "../../helper/pfmMgmt/pfEndPointDet";
// import { Form, Row, Col } from "react-bootstrap";
import { Input } from "antd";

const { TextArea } = Input;
export default class PfEndPoint extends React.Component {
  constructor(props) {
    super(props);
    const stateData = {
      tnnt_id: global.config.tnnt_id,
      username: "",
      role_id: global.config.user_role,
      is_loading: false,
      selectedData: undefined,
      editable: undefined,
      com_id:2,
      is_active: true,
      id: "",
      // task_1 : variable_declare

      int_ms_id: "",
      text_end_point: "",
      int_api_method_id: "",
      text_url: "",
      text_header_token: "",
      text_req_msg: "",
      text_exp_resp_msg: "",
      text_act_resp_msg: "",
      int_test_result: "",


    };
    if (props.data !== undefined) {
      stateData.editable = props.editable;
      stateData.id = props.data;
    }

    this.state = {
      ...stateData,
    };
  }
  componentDidMount() {
    const { editable } = this.state;
    const username = global.config.username;
    if (username != null && username !== undefined) {
      this.setState({
        username: username,
        tnnt_id: global.config.tnnt_id,
      });
    }

    editable !== undefined && this.getRecord();
  }

  getRecord() {
    const { id, tnnt_id } = this.state;

    const filter = {
      id: id,
      tnnt_id: tnnt_id,
    };

    SampleHelper.getRecord(filter)
      .then((data) => {
        this.setState({
          // update the state of the component
        int_ms_id: data[0].ms_id,
        text_end_point: data[0].end_point,
        int_api_method_id: data[0].api_method_id,
        text_url: data[0].url,
        text_header_token: data[0].header_token,
        text_req_msg: data[0].req_msg,
        text_exp_resp_msg: data[0].exp_resp_msg,
        text_act_resp_msg: data[0].act_resp_msg,
        int_test_result: data[0].test_result,
          is_active: data[0].is_active == "active" ? true : false,
        });
      })
      .catch((err) => {
        console.log(err);
      });
  }

  async insertRecord() {
    const {
      tnnt_id,
      username,
      // task_2 : all declared variable add here

      int_ms_id,
      text_end_point,
      int_api_method_id,
      text_url,
      text_header_token,
      text_req_msg,
      text_exp_resp_msg,
      text_act_resp_msg,
      int_test_result,


    } = this.state;

    try {
      const alertInitial = "";
      let alertText = alertInitial;

      //Validation
            if (int_ms_id === undefined){
                 alertText += ".Microservices Name\n ";
            }
            if (text_end_point ===""){
                 alertText += ".End Point\n ";
            }
            if (int_api_method_id === undefined){
                 alertText += ".Api Method\n ";
            }
            if (text_url ===""){
                 alertText += ".URL\n ";
            }



      if (alertText !== alertInitial) {
        Swal.fire({
          title: "Fill these fields:\n",
          html:
            '<pre style="display: flex;text-align: justify;flex-direction: column;align-items: center;line-height: 1.5">' +
            alertText +
            "</pre>",
          confirmButtonColor: Colors.primaryColor,
          width: Colors.width,
          allowOutsideClick: false,
        });
        return;
      }

      const data = {
        // task_3 : add more properties to data

        ms_id: int_ms_id,
        end_point: text_end_point,
        api_method_id: int_api_method_id,
        url: text_url,
        header_token: text_header_token,
        req_msg: text_req_msg,
        exp_resp_msg: text_exp_resp_msg,
        act_resp_msg: text_act_resp_msg,
        test_result: int_test_result,


        lc_status_id: 1,
        created_by: username,
        tnnt_id: tnnt_id,
      };

      this.setState({ is_loading: true });
      SampleHelper.insertRecord(data)
        .then((data) => {
          if (data.code == 200) {
            this.props.getData();
            Swal.fire({
              text: "Record Id: " + data.id + " created successfully.",
              confirmButtonColor: Colors.primaryColor,
              width: Colors.width,
              allowOutsideClick: false,
            });
            this.props.setVisibility(false);
            this.setState({ is_loading: false });
          } else if (data.code === 101) {
            Swal.fire({
              text: "Error",
              confirmButtonColor: Colors.red,
              width: Colors.width,
              allowOutsideClick: false,
            });
            this.setState({ is_loading: false });
          } else {
            Swal.fire({
              text: data.msg,
              confirmButtonColor: Colors.red,
              width: Colors.width,
              allowOutsideClick: false,
            });
            this.setState({ is_loading: false });
          }
        })
        .catch((err) => {
          Swal.fire({
            text: err,
            confirmButtonColor: Colors.red,
            width: Colors.width,
            allowOutsideClick: false,
          });
          console.log(err);
        });
    } catch (err) {
      console.log(err);
    }
  }

  async updateRecord() {
    const {
      id,
      is_active,
      tnnt_id,
      username,
      // task_2 : all declared variable add here

      int_ms_id,
      text_end_point,
      int_api_method_id,
      text_url,
      text_header_token,
      text_req_msg,
      text_exp_resp_msg,
      text_act_resp_msg,
      int_test_result,


    } = this.state;

    try {
      const alertInitial = "";
      let alertText = alertInitial;

      //Validation
            if (int_ms_id === undefined){
                 alertText += ".Microservices Name\n ";
            }
            if (text_end_point ===""){
                 alertText += ".End Point\n ";
            }
            if (int_api_method_id === undefined){
                 alertText += ".Api Method\n ";
            }
            if (text_url ===""){
                 alertText += ".URL\n ";
            }



      if (alertText !== alertInitial) {
        Swal.fire({
          title: "Fill these fields:\n",
          html:
            '<pre style="display: flex;text-align: justify;flex-direction: column;align-items: center;line-height: 1.5">' +
            alertText +
            "</pre>",
          confirmButtonColor: Colors.primaryColor,
          width: Colors.width,
          allowOutsideClick: false,
        });
        return;
      }

      const data = {
        id: id,
        // task_3 : add more properties to data

        ms_id: int_ms_id,
        end_point: text_end_point,
        api_method_id: int_api_method_id,
        url: text_url,
        header_token: text_header_token,
        req_msg: text_req_msg,
        exp_resp_msg: text_exp_resp_msg,
        act_resp_msg: text_act_resp_msg,
        test_result: int_test_result,



        lc_status_id: 1,
        is_active: is_active == false ? "inactive" : "active",
        created_by: username,
        tnnt_id: tnnt_id,
      };

      this.setState({ is_loading: true });
      SampleHelper.updateRecord(data)
        .then((data) => {
          if (data.code == 200) {
            this.props.getData();
            Swal.fire({
              text: "Record Id: " + id + " updated successfully.",
              confirmButtonColor: Colors.primaryColor,
              width: Colors.width,
              allowOutsideClick: false,
            });
            this.props.setVisibility(false);
            this.setState({ is_loading: true });
          } else if (data.code === 101) {
            Swal.fire({
              text: "Error",
              confirmButtonColor: Colors.red,
              width: Colors.width,
              allowOutsideClick: false,
            });
            this.setState({ is_loading: false });
          } else {
            Swal.fire({
              text: data.msg,
              confirmButtonColor: Colors.red,
              width: Colors.width,
              allowOutsideClick: false,
            });
            this.setState({ is_loading: false });
          }
        })
        .catch((err) => {
          Swal.fire({
            text: err,
            confirmButtonColor: Colors.red,
            width: Colors.width,
            allowOutsideClick: false,
          });
          console.log(err);
        });
    } catch (err) {
      console.log(err);
    }
  }

  render() {
    const { setVisibility } = this.props;
    const {
      editable,
      is_loading,
      is_active,
      // task_2 : all declared variable add here

      int_ms_id,
      text_end_point,
      int_api_method_id,
      text_url,
      text_header_token,
      text_req_msg,
      text_exp_resp_msg,
      text_act_resp_msg,
      int_test_result,


    } = this.state;

    return (
      <div className={styles.mainWrapper}>
        {is_loading && (
          <div className={"loadingWrapper"}>
            <div className={"innerLoadingWrapper"}>
              <div class="bouncing-loader">
                <div></div>
                <div></div>
                <div></div>
              </div>
            </div>
          </div>
        )}

        <div className={styles.wrapper} onClick={(e) => e.stopPropagation()}>
          <img
            src="/assets/close-red.png"
            className={styles.closeButton}
            onClick={() => setVisibility(false)}
          />
          <div>
            <p className={styles.title}>
              {editable == undefined ? "Create Record" : editable ? "Update Record" : "View Record"}
            </p>
            {/*// task_4 : build logic per column and specific to data type.*/}
             <div className={styles.sideWrapper}>

                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>Microservices Name:<span
            style={{ color: "red", marginLeft: "3px", fontSize: "20px" }} >
            *
            </span>
            </p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                <CustomInput
                                 input type="number"
                                    value={int_ms_id}
                                    onChange={(e) =>
                                    this.setState({
                                        int_ms_id: e.target.value,
                                    })
                                    }
                                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{int_ms_id}</p>
                                </div>
                            )}
                            </div>
                        </div>
            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>End Point:<span
            style={{ color: "red", marginLeft: "3px", fontSize: "20px" }} >
            *
            </span>
            </p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                <CustomInput
                                 input type="text"
                                    value={text_end_point}
                                    onChange={(e) =>
                                    this.setState({
                                        text_end_point: e.target.value,
                                    })
                                    }
                                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{text_end_point}</p>
                                </div>
                            )}
                            </div>
                        </div>


            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>Api Method:<span
            style={{ color: "red", marginLeft: "3px", fontSize: "20px" }} >
            *
            </span>
            </p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                <CustomInput
                                 input type="number"
                                    value={int_api_method_id}
                                    onChange={(e) =>
                                    this.setState({
                                        int_api_method_id: e.target.value,
                                    })
                                    }
                                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{int_api_method_id}</p>
                                </div>
                            )}
                            </div>
                        </div>
            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>URL:<span
            style={{ color: "red", marginLeft: "3px", fontSize: "20px" }} >
            *
            </span>
            </p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                <CustomInput
                                 input type="text"
                                    value={text_url}
                                    onChange={(e) =>
                                    this.setState({
                                        text_url: e.target.value,
                                    })
                                    }
                                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{text_url}</p>
                                </div>
                            )}
                            </div>
                        </div>


            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>Header Token:</p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                <CustomInput
                                 input type="text"
                                    value={text_header_token}
                                    onChange={(e) =>
                                    this.setState({
                                        text_header_token: e.target.value,
                                    })
                                    }
                                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{text_header_token}</p>
                                </div>
                            )}
                            </div>
                        </div>


            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>Request Message:
			    </p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                              
                                 <TextArea
                  showCount
                  maxLength={100}
                  value={text_req_msg}
                  onChange={(e) =>
                    this.setState({
                      text_req_msg: e.target.value,
                    })}
                  name="report_descr"
                  placeholder="Actual Response Message"
                  required
                  
                  style={{
                    height: 120,
                    resize: "none",
                  }}
                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{text_req_msg}</p>
                                </div>
                            )}
                            </div>
                        </div>
            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>Expected Response Message:
			    </p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                

                 <TextArea
                  showCount
                  maxLength={100}
                  value={text_exp_resp_msg}
                  onChange={(e) =>
                    this.setState({
                        text_exp_resp_msg: e.target.value,
                    })}
                  name="report_descr"
                  placeholder="Expected Response Message"
                  required
                  
                  style={{
                    height: 120,
                    resize: "none",
                  }}
                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{text_exp_resp_msg}</p>
                                </div>
                            )}
                            </div>
                        </div>
            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>Actual Response Message:
			    </p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                

                 <TextArea
                  showCount
                  maxLength={100}
                  value={text_act_resp_msg}
                  onChange={(e) =>
                    this.setState({
                        text_act_resp_msg: e.target.value,
                    })}
                  name="report_descr"
                  placeholder="Actual Response Message"
                  required
                  
                  style={{
                    height: 120,
                    resize: "none",
                  }}
                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{text_act_resp_msg}</p>
                                </div>
                            )}
                            </div>
                        </div>
            
                        <div className={styles.leftWrapper}>
                            <div className={styles.inputAlignment}>
                            <p>Test Result:</p>
                            {editable != false ? (
                                <div className={styles.inputCustom}>
                                <CustomInput
                                 input type="number"
                                    value={int_test_result}
                                    onChange={(e) =>
                                    this.setState({
                                        int_test_result: e.target.value,
                                    })
                                    }
                                />
                                </div>
                            ) : (
                                <div className={styles.viewField}>
                                <p>{int_test_result}</p>
                                </div>
                            )}
                            </div>
                        </div>
            
                 </div>

            <div className={styles.inputAlignment}>
              <p className={`mandatory`}><span style={{ color: "red", marginLeft: "3px", fontSize: "15px" }}>* are mandatory fields</span></p>
            </div>
            <div
              className={styles.inputAlignment}
              style={{
                justifyContent: "space-around",
                display: "flex",
              }}
            >
              {editable !== undefined && (
                <div>
                  <label className="switch">
                    <input
                      type="checkbox"
                      checked={is_active}
                      onChange={(e) =>
                        this.setState({
                          is_active: e.target.checked,
                        })
                      }
                      disabled={editable == false}
                    />
                    <span className="slider round"></span>
                  </label>
                  <p className={styles.statusText}>
                    {is_active ? "Active" : "Inactive"}
                  </p>
                </div>
              )}
            </div>
            {editable != false && (
              <div className={styles.button}>
                <button
                  className={`button`}
                  onClick={() =>
                    editable == undefined
                      ? this.insertRecord()
                      : editable && this.updateRecord()
                  }
                >
                  {editable == undefined ? "Create" : editable && "Update"}
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  }
}